name: mandobaswaaq
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  get: ^4.3.8
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  url_launcher: ^6.0.5
  flutter_launcher_icons: ^0.9.2
  flutter_screenutil: ^5.2.0
  intl: ^0.17.0
  bloc: ^8.1.0
  awesome_dialog: ^3.0.2
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  flutter_offline: ^2.0.0
  flutter_svg: ^1.1.5
  custom_refresh_indicator: ^2.0.1
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.4.0
  data_table_2: ^2.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: hanimation
      fonts:
        - asset: assets/fonts/hanimation.ttf